Port to meson
linuxmint/slick-greeter pull request #181
Opened 2021-03-18 15:21 UTC by ItzSwirlz

It's been a journey.

Sicne there is no vapi or anytihng by default for xext, I saw that Makefile builds xext for C but not Vala, so @eschwartz hacked it for me (thanks)

2021-03-18 16:05 UTC, collinss requested changes

2021-03-18 16:05 UTC, collinss commented on tests/meson.build
> +  '../src/xsync.vapi',
You already have all of these in sgreeter_sources. Just add that to the list (without quotes). Meson will handle the relative paths.

2021-03-18 16:19 UTC, ItzSwirlz commented on tests/meson.build
> +  '../src/xsync.vapi',
You can't-there are conflicting file names in the tests folder and src/ folder. sgreeter_sources contains it

2021-03-18 16:25 UTC, ItzSwirlz commented on files/meson.build
> +install_subdir('usr', install_dir : '/')
If you use the prefixdir you get /usr/usr
![Screenshot from 2021-03-18 12-22-31](https://user-images.githubusercontent.com/24401303/111660924-f35a3280-87e4-11eb-90b3-9b2b366e55dd.png)

2021-03-18 16:26 UTC, ItzSwirlz commented on files/meson.build
> +install_subdir('usr', install_dir : '/')
No, installing subdir '.' won't fix this

2021-03-18 16:29 UTC, ItzSwirlz commented on tests/meson.build
> +  '../src/xsync.vapi',
sgreeter_sources treats the files as if they are int here as ./(file). it doesn'ta utomatically ../src it, so you get file doesn't exist

2021-03-18 16:45 UTC, ItzSwirlz commented on files/meson.build
> +install_subdir('usr', install_dir : '/')
Also this is done in cinnamon..?
```
install_subdir(
    'files',
    install_dir: '/',
    strip_directory: true,
)
```

2021-03-18 17:03 UTC, collinss commented on files/meson.build
> +install_subdir('usr', install_dir : '/')
Yes, you also need to include the `strip_directory: true` line so that it doesn't end up in usr/usr/ (see https://mesonbuild.com/Reference-manual.html#install_subdir). In cinnamon the reason we install to / is because the `files` directory also contains `etc/` which is outside the tree of `prefixdir`, so it is necessary, but generally it is preferred to use `prefixdir` if possible.

Basically, it should be:
```
install_subdir(
    'usr',
    install_dir: prefixdir,
    strip_directory: true,
)
```

2021-03-18 17:10 UTC, collinss commented on tests/meson.build
> +  '../src/xsync.vapi',
There are only 2 files in sgreeter_sources that don't get included in the executable. You can rename `sgreeter_sources` to `sgreeter_common`, and move those 2 files to another list like so:
```
sgreeter_sources = [
    <the other 2 files>,
    sgreeter_common,
]
```
Then you can add sgreeter_common to the list of test sources. That will reduce duplication, and make it much easier to read and maintain.

2021-03-20 00:05 UTC, ItzSwirlz commented on tests/meson.build
> +  '../src/xsync.vapi',
That still won't do anything. the ../src must be there, otherwise it looks for ./(filename). You can't just say a variable from another directory.

var1 = 'file1.vala' in src directory
files = var1 in test directory

It doesn't work-it's looking for test/file1.vala instead of src/var1.vala.

No matter what happens the ../src needed, are you saying have a sgreeter_common in the tests/meson.build?

2021-03-21 02:27 UTC, collinss commented on tests/meson.build
> +  '../src/xsync.vapi',
Sorry, I forgot that you'll need to pass that list (sgreeter_common) to the files() function like so:
`sgreeter_common_files = files(sgreeter_common)`
and then pass sgreeter_common_files as the list of sources for the test executable.

2021-03-21 14:10 UTC, ItzSwirlz commented on tests/meson.build
> +  '../src/xsync.vapi',
Ah. Okay

2021-03-21 22:35 UTC, ItzSwirlz commented on tests/meson.build
> +  '../src/xsync.vapi',
Sorry buddy... yikes (chuckles)
![Screenshot from 2021-03-21 18-35-16](https://user-images.githubusercontent.com/24401303/111923161-3aaa2280-8a74-11eb-8b01-274c6eb8c0d3.png)
![Screenshot from 2021-03-21 18-35-12](https://user-images.githubusercontent.com/24401303/111923162-3aaa2280-8a74-11eb-8d17-3ea96d8eef97.png)
![Uploading Screenshot from 2021-03-21 18-35-02.png…]()

2021-03-22 00:39 UTC, collinss commented on tests/meson.build
> +  '../src/xsync.vapi',
No, the files() call needs to be in src/meson.build, not tests/meson.build. The files() function basically just makes the paths relative to the path where the function was called, so putting it in tests/meson.build is going to give you the same result as just passing a bare list.

2021-03-22 12:27 UTC, ItzSwirlz commented on tests/meson.build
> +  '../src/xsync.vapi',
Gotcha, thanks.

2021-03-25 02:43 UTC, ItzSwirlz commented
Hold PR, don't merge yet. I found a thing with config.h causing unneccessary c_args. (See: https://github.com/Ubuntu-Cinnamon-Remix/nemo-wipe/commit/600bdc7b4c9f2c941e131142d66af6036b1b76d9)

2021-11-23 15:58 UTC, clefebvre commented
Closing, inactive for too long.

2021-11-23 15:58 UTC, closed without merging